#!/bin/bash
# Generate prefixes.conf for the XDP filter from two static config files:
#   nat_pools.conf      -> class 1 (CLASS_NATPOOL): CGNAT/SNAT pool prefixes,
#                          matched in the kernel conntrack (bpf_xdp_ct_lookup)
#   client_ranges.conf  -> class 2 (CLASS_ROUTED): routed public client prefixes
#                          that are notrack, matched against the outbound-SYN LRU
#
# Both are STATIC — no dependency on the (dynamic) routing table. Output lines
# are "CIDR class". Run anywhere; the result is host-independent.
#
# Edit the two .conf files to match YOUR network before deploying. The shipped
# values are RFC 5737 documentation ranges and must be replaced.
set -euo pipefail

POOLS_FILE="${1:-nat_pools.conf}"
RANGES_FILE="${2:-client_ranges.conf}"

for f in "$POOLS_FILE" "$RANGES_FILE"; do
	if [ ! -r "$f" ]; then
		echo "error: cannot read '$f'" >&2
		exit 1
	fi
done

# strip '#' comments and whitespace, drop blank lines
strip() { sed 's/#.*//' "$1" | tr -d ' \t' | grep -v '^$' || true; }

{
	echo "# generated by gen_prefixes.sh — do not edit by hand"
	echo "# class 1 = NAT pool (conntrack), class 2 = routed client range (LRU)"
	strip "$POOLS_FILE"  | while read -r cidr; do echo "$cidr 1"; done
	strip "$RANGES_FILE" | while read -r cidr; do echo "$cidr 2"; done
}
